### ISSUE TITLE
你好，请问有主办方的联系方式吗？

### ISSUE THREAD

**Issue by XiantaoHu** [Hello-2073/Cifar10-Adversarial-Competition#12]

**Comment by Hello-2073** [comment]
您好，“Cifar-10 数字世界 无限制对抗攻击竞赛”是由北京航空航天大学”人工智能安全导论“课程开设的比赛，发布在AI-Challenge平台上，比赛网站目前只能校内访问。您可以通过联系课程教师进一步了解该比赛，联系方式http://irip.buaa.edu.cn/andyguo/index.html。
